# Generated by Django 2.0.4 on 2018-04-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_app', '0002_auto_20180409_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
