# Generated by Django 2.0.4 on 2018-04-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_app', '0003_user_pr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pr',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nr',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
